- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/chron.yml
    - include: tasks/firefox_profiles.yml
    - include: tasks/setup_profiles.yml
    - include: tasks/firewall.yml
    - include: tasks/samba.yml
